export const SEND_MESSAGE = {
  SUCCESS: "SEND_MESSAGE_SUCCESS",
  FAIL: "SEND_MESSAGE_FAIL",
  LOADING: "SEND_MESSAGE_LOADING",
  RESET: "SEND_MESSAGE_RESET",
};

export const UPDATE_MESSAGE = {
  SUCCESS: "UPDATE_MESSAGE_SUCCESS",
  FAIL: "UPDATE_MESSAGE_FAIL",
  LOADING: "UPDATE_MESSAGE_LOADING",
  RESET: "UPDATE_MESSAGE_RESET",
};

export const GET_MESSAGES = {
  SUCCESS: "GET_MESSAGES_SUCCESS",
  FAIL: "GET_MESSAGES_FAIL",
  LOADING: "GET_MESSAGES_LOADING",
  RESET: "GET_MESSAGES_RESET",
};

export const GET_A_MESSAGES = {
  SUCCESS: "GET_A_MESSAGE_SUCCESS",
  FAIL: "GET_A_MESSAGE_FAIL",
  LOADING: "GET_A_MESSAGE_LOADING",
  RESET: "GET_A_MESSAGE_RESET",
};

export const DELETE_MESSAGE = {
  SUCCESS: "DELETE_MESSAGE_SUCCESS",
  FAIL: "DELETE_MESSAGE_FAIL",
  LOADING: "DELETE_MESSAGE_LOADING",
  RESET: "DELETE_MESSAGE_RESET",
};
