export const SEND_MESSAGE = {
  SUCCESS: "SEND_MESSAGE_SUCCESS",
  FAIL: "SEND_MESSAGE_FAIL",
  LOADING: "SEND_MESSAGE_LOADING",
  RESET: "SEND_MESSAGE_RESET",
};

export const UPDATE_MESSAGE = {
  SUCCESS: "UPDATE_MESSAGE_SUCCESS",
  FAIL: "UPDATE_MESSAGE_FAIL",
  LOADING: "UPDATE_MESSAGE_LOADING",
  RESET: "UPDATE_MESSAGE_RESET",
};
