export const RESET = "PARCEL_RESET";

export const GET_PARCELS = {
  SUCCESS: "GET_PARCEL_SUCCESS",
  LOADING: "GET_PARCEL_LOADING",
  FAIL: "GET_PARCEL_FAIL",
  RESET: "GET_PARCEL_RESET",
};

export const ADD_PARCEL = {
  SUCCESS: "ADD_PARCEL_SUCCESS",
  LOADING: "ADD_PARCEL_LOADING",
  FAIL: "ADD_PARCEL_FAIL",
  RESET: "ADD_PARCEL_RESET",
};

export const UPDATE_PARCEL = {
  SUCCESS: "UPDATE_PARCEL_SUCCESS",
  LOADING: "UPDATE_PARCEL_LOADING",
  FAIL: "UPDATE_PARCEL_FAIL",
  RESET: "UPDATE_PARCEL_RESET",
};

export const DELETE_PARCEL = {
  SUCCESS: "DELETE_PARCEL_SUCCESS",
  LOADING: "DELETE_PARCEL_LOADING",
  FAIL: "DELETE_PARCEL_FAIL",
  RESET: "DELETE_PARCEL_RESET",
};
