export const LOGIN = {
  LOGOUT: "LOGOUT",
  SUCCESS: "LOGIN_SUCCESS",
  FAIL: "LOGIN_FAIL",
  LOADING: "LOGIN_LOADING",
  RESET: "LOGIN_RESET",
};

export const SIGNUP = {
  SUCCESS: "SIGNUP_SUCCESS",
  FAIL: "SIGNUP_FAIL",
  LOADING: "SIGNUP_LOADING",
  RESET: "SIGNUP_RESET",
};

export const UPDATE_USER = {
  SUCCESS: "UPDATE_USER_SUCCESS",
  FAIL: "UPDATE_USER_FAIL",
  LOADING: "UPDATE_USER_LOADING",
  RESET: "UPDATE_USER_RESET",
};
