export const CHANGE_LOGIN_REDIRECT = "CHANGE_LOGIN_REDIRECT";
export const SET_TRACK_ID = "SET_TRACK_ID";
export const CHANGE_PANEL = "CHANGE_PANEL";

export const GET_STATIONS = {
  SUCCESS: "GET_STATIONS_SUCCESS",
  FAIL: "GET_STATIONS_SUCCESS",
};
